### ISSUE TITLE
Error when I try to use loader to load arff file with utf-8 characters

### ISSUE THREAD

**Issue by pigeon2049** [fracpete/python-weka-wrapper3#20]
Dear Developer:
English is not my mother tongue.
please excuse any errors on this issue.
I'm new to Weka.
I have made a fomatted arff file. And it just works fine when i load it in Weka Gui. (I have edited RunWeka.ini with fileEncoding=UTF-8)
I use this dataset for text classification and this dataset performs well when i do percentage split classsify with BayesNet Classifier. [result.txt](https://drive.google.com/open?id=1Xjr4iB0zXYetHttwqsnJBG8e0Tfh3Ih7)
But when i use python-weka-wrapper3:
>>>import weka.core.jvm as jvm
>>>jvm.start()
DEBUG:weka.core.jvm:Adding bundled jars
DEBUG:weka.core.jvm:Classpath=['D:\\Python\\lib\\site-packages\\javabridge\\jars\\rhino-1.7R4.jar', 'D:\\Python\\lib\\site-packages\\javabridge\\jars\\runnablequeue.jar', 'D:\\Python\\lib\\site-packages\\javabridge\\jars\\cpython.jar', 'D:\\Python\\lib\\site-packages\\weka\\lib\\python-weka-wrapper.jar', 'D:\\Python\\lib\\site-packages\\weka\\lib\\weka.jar']DEBUG:weka.core.jvm:MaxHeapSize=default
DEBUG:weka.core.jvm:Package support disabled
 from weka.core.converters import Loader, Saver
 loader = Loader(classname="weka.core.converters.ArffLoader")
 data = loader.load_file("D:\Cutwords\TrainingDocuments_Preprocessed.arff")
Exception in thread "Thread-0" java.io.IOException: Unable to determine structure as arff (Reason: java.lang.IllegalArgumentException: Attribute names are not unique! Causes: '涓?涓?' '涓?浜?' '涓?鍙?' '涓?鍙?' '涓?搴?' '涓?' '涓?' '涔?' '浜?' '浜?' '浜?' '浼?' '浣?' '浣?' '鍏?' '鍐?' '鍐?' '鍓?' '鍙?' '鍙?' '鍙?' '鍙?' '鍙?' '鍚?' '鍚?' '鍚?' '鍚?' '鍠?' '鍥?' '澧?' '澶?' '澶?' '澶?' '澶?' '濂?' '瀛?' '瀛?' '瀹?' '灏?' '灞?' '甯?' '骞?' '寮?' '寮?' '寰?' '蹇?' '蹇?' '鎯?' '鎯?' '鎴?' '鎸?' '鎺?' '鏂?' '鏃?' '鏃?' '鏄?' '鏄?' '鏇?' '鏈?' '鏉?' '姝?' '姹?' '娉?' '娓?' '鐗?' '鐢?' '鐢?' '鐢?' '鐪?' '鐪?' '鐪?' '鐭?' '鐭?' '绉?' '绉?' '缁?' '缁?' '鑳?' '鑸?' '瑙?' '璁?' '璇?' '璇?' '璇?' '璇?' '璇?' '璇?' '璧?' '璧?' '杩?' '杩?' '杩?' '閫?' '閫?' '闆?' '闆?' '闈?' '椋?' '椋?' ' 棣?' '涓?' '浜?' '浜?' '浠?' '鍒?' '鍓?' '鍗?' '鍗?' '鍙?' '鍚?' '鍚?' '鍝?' '鍠?' '鍥?' '澶?' '濞?' '灞?' '宸?' '甯?' '甯?' '骞?' '寮?' '寮?' '鎬?' '鎬?' '鎯?' '鎯?' '鎰?' '鎴?' '鎵?' '鎵?' '鎵?' '鎶?' '鎷?' '鎸?' '鎹?' '鎺?' '鎼?' '鎼?' '鎾?' '鎾?' '鎾?' '鏁?' '鏂?' '鏄?' '鏄?' '鏄?' '鏅?' '鏇?' '鏈?' '鏉?' '鏉?' '姝?' '姘?' '姹?' '娣?' '娓?' '鐑?' '鐖?' '鐙?' '鐜?' '鐞?' '鐞?' '鐢?' '鐢?' '鐢?' '绉?' '绔?' '绾?' '鑳?' '鑴?' '鑵?' '鑼?' '鑾?' '琛?' '瓒?' '璺?' '閫?' '閬?' '閮?' '閿?' '闆?' '闆?' '楠?' '涓?浠?' '涓?骞?' '涓?' '涓?' '涔?' '鍋?' '鍏?' '鍐?' '鍒?' '鍔?' '鍗?' '鍗?' '鍙?' '鍙?' '鍝?' '鍥?' '鍧?' '澶?' '寮?' '寰?' '鎬?' '鎭?' '鎭?' ' 鎴?' '鎵?' '鎶?' '鎺?' '鏀?' '鏉?' '鏉?' '娆?' '娓?' '鐞?' '鐨?' '鐮?' '绔?' '绛?' '缁?' '缃?' '鑳?' '璇?' '璧?' '璧?' '璧?' '瓒?' '杩?' '杩?' '閲?' '闃?' '闇?' '涓?' '涔?' '浜?' '浜?' '浣?' '鍏?' '鍏?' '鍑?' '鍑?' '鍔?' '鍙?' '鍧?' '濡?' '瀛?' '瀹?' '瀹?' '甯?' '寮?' '鎬?' '鎶?' '鏈?' '娌?' '鐐?' '绾?' '缃?' '鑲?' '璋?' '璐?' '璧?' '璺?' '韪?' '杞?' '杞?' '杈?' '閫?' '閫?' '閫?' '閾?' '閾?' '闄?' '涓?缁?' '浜?' '浠?' '浠?' '浼?' '淇?' '鍊?' '鍊?' '鍏?' '鍗?' '鍗?' '濂?' '瀹?' '瀹?' '灞?' '甯?' '骞?' '搴?' '鎬?' '鎴?' '鎴?' '鎵?' '鎷?' '鏀?' '鏀?' '鏈?浣?' '鏍?' '娆?' '婀?' '鐜?' '鐩?' '绉?' '绋?' '璇?' '璐?' '閲?' '闄?' '闄?' '涓?鍙?' '淇?' '鍋?' '鍏?' '鍒?' '鍗?' '鍙?' '鍞?' '鍞?' '鍧?' '瀹?' '搴?' '搴?' '鎵?' '鎷?' '鎷?' '鎸?' '鏉?' '姣?' '娌?' '鐗?' '鐢?' '绾?' '绾?' '鑰?' '瑁?' '璐?' '璐?' '杞?' '杈?' '閫?' '閫?' '閰?' '闂?' '椹?' '楂橀??' '涓?涓?' '涓?浠?' '涓?澶?' '涓?鎵?' '涓?鎵?' '涓?绾?' '鍏?' '鍏?' '鍗?' '澶?' '瀛?' '鎷?' '鎽?' '鏃?' '绫?' '缇?' '鑳?' '璇?' '璧?' '闀?' '涓?鏂?' '鍒?' '灞?' '蹇??' '鎵?' '鎼?' '鏃?' '鏈?' '鐗?' '鐮?' '绁?' '韬?' '閬?' '閽?' '閿?' '楂橀??' '涓?鏋?' '涓?鏋?' '浠?' '浣?' '淇?' '鍐?' '鍖?' '鍙?' '鍙?' '鍚?' '灞?' '宸?' '宸?' '甯?' '鎵?' '鎸?' '鎺?' '鏋?' '鏋?' '鏋?' '鏍?' '姝?' '鐐?' '鐩?' '鐮?' '鑸?' '鑸?' '鑻?' '杞?' '杩?' '閫?浼?' '椹?' '涓?澶?' '涔?' '浜?' '浠?' '浼?' '鍏?' '鍘?' '鍠?' '鍥?' '澶?' '澶?' '瀵?' '宀?' '鎱?' '鎽?' '鎽?' '鏃?' '鏈?鍏?' '妗?' '娌?' '娲?' '鐖?' ' 鑺?' '璋?' '璧?' '璧?' '閫?' '闀?' '闂?' '浼?' '浼?' '鍊?' '鍒?' '鍒?' '鍓?' '鍗?' '鍩?' '澶ч??' '濞?' '姊?' '鑻?' '闊?' '涓?澶?' '涓?灞?' '涓?鎴?' '浜?' '淇?' '淇?' '鍏?' '鍔?' '鍦?' '鍧?' '蹇?' '鎸?' '鎹?' '鎼?' '鏋?' '鏍?' '鏍?' '娌?' '鐏?' '绌?' '缇?' '鑲?' '鑲?' '鑻?' '鑽?' '鑿?' '棰?' '椋?' '楗?' '椹?' '楦?' '榛?' '涓?绉?' '涔?' '浠?' '鍑?' '鍓?' '鍓?' '鍖?' '鍗?' '鍦?' '甯?' '搴?' '鎬?' '鎶?' '鏈?' '姘?' '娴?' '鐐?' '鐙?' '鐙?' '鐜?' '鐮?' '璺?' '閲?' '閾?' '椴?' '涓?涓?' '涓?浜?' '涓?鍗?' '涓?鍛?' '涓?鐪?' '涓?琚?' '涓?椤?' '鍋?' '鍑?' '鍙?' '鍛?' '鍜?' '鍠?' '濡?' '濡?' '濞?' '濞?' '瀚?' '瀚?' '瀹?' '瀵?' '寮?鍙?' '蹇?' '鎬?' '鎭?' '鎰?' '鎵?' '鎷?' '鎺?' '鏁?' '鏂?' '鏃?' '鏅?' '姣?' '娲?' '婊?' '鐖?' '鐖?' '鐢?' '鐣?' '鐪?' '绾?' '琛?' '璐?' '瓒?' '璺?' '闂?' '闈?' '楠?' ).
        at weka.core.converters.ArffLoader.getStructure(ArffLoader.java:1251)
        at weka.core.converters.ArffLoader.getDataSet(ArffLoader.java:1280)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python\lib\site-packages\weka\core\converters.py", line 88, in load_file
    return Instances(javabridge.call(self.jobject, "getDataSet", "()Lweka/core/Instances;"))
  File "D:\Python\lib\site-packages\javabridge\jutil.py", line 887, in call
    result = fn(*nice_args)
  File "D:\Python\lib\site-packages\javabridge\jutil.py", line 854, in fn
    raise JavaException(x)
javabridge.jutil.JavaException: Unable to determine structure as arff (Reason: java.lang.IllegalArgumentException: Attribute names are not unique! Causes: '涓�涓�' '涓�浜�' '涓�鍙�' '涓�鍙�' '涓�搴�' '涓�' '涓�' '涔�' '浜�' '浜�' '浜�' '浼�' '浣�' '浣�' '鍏�' '鍐�' '鍐�' '鍓�' '鍙�' '鍙�' '鍙�' '鍙�' '鍙�' '鍚�' '鍚�' '鍚�' '鍚�' '鍠�' '鍥�' '澧�' '澶�' '澶�' '澶�' '澶�' '濂�' '瀛�' '瀛�' '瀹�' '灏�' '灞�' '甯�' '骞�' '寮�' '寮�' '寰�' '蹇�' '蹇�' 

It seems to be a problem of file encoding.
And i tried to find how to change fileEncoding in python-weka-wrapper3Docs and haven't find yet.
Here is the dataset [TrainingDocuments_Preprocessed.arff](https://drive.google.com/file/d/1IXSiJGNeJiIAskYvhndt7SrSdCxzekLZ/view?usp=sharing)
And this is stop-words file [stopwordsFile](https://drive.google.com/open?id=11BRsXfc0zKd0cPW5r7qsjwHJnJzMGI6I)
Can you help me?

**Comment by pigeon2049** [comment]
Or i made a wrong formatted arff file?
Anyone can help me?

**Comment by fracpete** [comment]
Try setting the `_JAVA_OPTIONS` environment variable, using the following value:
```
-Dfile.encoding=UTF-8
```

If you're running this from an IDE, you should be able to set this environment variable for the project/interpreter.

**Comment by fracpete** [comment]
You can set environment variables in your Python code with `os.environ`, e.g., the file encoding:
```python
import weka.core.jvm as jvm
import os
os.environ["_JAVA_OPTIONS"] = "-Dfile.encoding=UTF-8"
jvm.start(packages=True)
...
jvm.stop()
```

**Comment by pigeon2049** [comment]
Thank you.
Problem solved.
