### ISSUE TITLE
AttributeError: 'Instance' object has no attribute 'encode' 

### ISSUE THREAD

**Issue by farzadhallaji** [fracpete/python-weka-wrapper3#21]
for simple code :
```
tree.build_classifier(labledDataSet)
eval = Evaluation(labledDataSet)
eval.evaluate_model(tree, test)
```
i got this error : 
```
DEBUG:weka.core.jvm:MaxHeapSize=default
DEBUG:weka.core.jvm:Package support enabled
Picked up _JAVA_OPTIONS: -Dfile.encoding=UTF-8
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by weka.core.WekaPackageClassLoaderManager (file:/home/farzad/anaconda3/envs/mix/lib/python3.5/site-packages/weka/lib/weka.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of weka.core.WekaPackageClassLoaderManager
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Traceback (most recent call last):
  File "main.py", line 187, in <module>
    raise e
  File "main.py", line 165, in <module>
    eval.evaluate_model(tree, test)
  File "/home/farzad/anaconda3/envs/mix/lib/python3.5/site-packages/weka/classifiers.py", line 1942, in evaluate_model
    classifier.jobject, args)
  File "/home/farzad/anaconda3/envs/mix/lib/python3.5/site-packages/javabridge/jutil.py", line 937, in static_call
    nice_args = get_nice_args(args, args_sig)
  File "/home/farzad/anaconda3/envs/mix/lib/python3.5/site-packages/javabridge/jutil.py", line 1144, in get_nice_args
    for arg, subsig in zip(args, sig)]
  File "/home/farzad/anaconda3/envs/mix/lib/python3.5/site-packages/javabridge/jutil.py", line 1144, in <listcomp>
    for arg, subsig in zip(args, sig)]
  File "/home/farzad/anaconda3/envs/mix/lib/python3.5/site-packages/javabridge/jutil.py", line 1211, in get_nice_arg
    objs = [get_nice_arg(subarg, sig[1:]) for subarg in arg]
  File "/home/farzad/anaconda3/envs/mix/lib/python3.5/site-packages/javabridge/jutil.py", line 1211, in <listcomp>
    objs = [get_nice_arg(subarg, sig[1:]) for subarg in arg]
  File "/home/farzad/anaconda3/envs/mix/lib/python3.5/site-packages/javabridge/jutil.py", line 1179, in get_nice_arg
    return env.new_string_utf(arg)
  File "_javabridge.pyx", line 1662, in _javabridge.JB_Env.new_string_utf
AttributeError: 'Instance' object has no attribute 'encode'

```

**Comment by fracpete** [comment]
What version of javabridge are you using? Use the following command to output the versions for your Python packages in your environment:
```
pip freeze
```

**Comment by farzadhallaji** [comment]
javabridge==1.0.18

**Comment by fracpete** [comment]
That's way too old. The current release is 1.0.18. It's a shame that Anaconda doesn't seem to update their repositories very often. Instead, you should install it straight from pypi.org:
  https://pypi.org/project/javabridge/
Personally, I use virtualenv rather than Anaconda, as it has a much smaller footprint.

**Comment by farzadhallaji** [comment]
javabridge version is 1.0.18
i got again same error

**Comment by fracpete** [comment]
Please post minimal code and datasets with which you can replicate this problem.

**Comment by farzadhallaji** [comment]
```
def splitTrainSet(data,m_numLabledData=10) :

    total = data.num_instances
    labeled_amount = int(m_numLabledData * total / 100)
    unlabeled_amount = total - labeled_amount

    rand = Random(1)
    data.randomize(rand)

    labledDataSet = Instances.create_instances(data.relationname,data.attributes(),labeled_amount)
    UnlabledDataSet = Instances.create_instances(data.relationname,data.attributes(),unlabeled_amount)

    labledDataSet.class_is_last()
    UnlabledDataSet.class_is_last()

    for i in range(labeled_amount) :
        labledDataSet.add_instance(data.get_instance(i))

    labledDataSet.randomize(rand)

    for i in range(unlabeled_amount) :
        UnlabledDataSet.add_instance(data.get_instance(labeled_amount + i))

    UnlabledDataSet.randomize(rand)
    UnlabledDataSet.no_class()

    return labledDataSet,UnlabledDataSet
```
and in main :

```
from weka.core.converters import Loader
from weka.core.dataset import Instances
from weka.core.dataset import Instance
from weka.classifiers import Evaluation
from weka.classifiers import Classifier
import weka.core.jvm as jvm
import os
os.environ["_JAVA_OPTIONS"] = "-Dfile.encoding=UTF-8"
jvm.start(packages=True)

loader = Loader("weka.core.converters.ArffLoader")


datasaetsName = ["breast-cancer"]
PathToData = "./originDataset/"
data = loader.load_file(PathToData + dataset + "/train.arff")
test =loader.load_file(PathToData + dataset + "/test.arff")
data.class_is_last()
test.class_is_last()
labledDataSet , UnlabledDataSet = splitTrainSet(data);
     
tree = Classifier(classname="weka.classifiers.trees.J48", options=["-A"])
tree.build_classifier(labledDataSet)
            
eval = Evaluation(labledDataSet)
eval.evaluate_model(tree, test)

```

**Comment by fracpete** [comment]
You are using the wrong test method. Instead of `evaluate_model` (which takes command-line arguments), use the following:
```
eval.test_model(tree, test)
```
Hence the error message of the missing `encode` method, since the `Instances` object is not a string.

**Comment by farzadhallaji** [comment]
Thanks :+1: :heart:
