### ISSUE TITLE
Example from documentation "Create dataset from matrices" raises an exception

### ISSUE THREAD

**Issue by programmingpixels** [fracpete/python-weka-wrapper3#35]
Sorry, failure on my part to start the VM!

The example I'm following is: http://fracpete.github.io/python-weka-wrapper/examples.html#create-dataset-from-matrices

My library versions are:
python-weka-wrapper3 0.2.3
numpy 1.21.1
javabridge 1.0.19

Python 3.9.6 (default, Jul 26 2021, 11:20:45) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import numpy as np
>>> from weka.core.dataset import create_instances_from_matrices

>>> x = np.random.randn(10, 5)
>>> y = np.random.randn(10)
>>> dataset = create_instances_from_matrices(x, y, name="generated from matrices")

Traceback (most recent call last):
  File "/home/danny/Envs/wtest/lib/python3.9/site-packages/weka/core/dataset.py", line 1693, in create_instances_from_matrices
    if np.issubdtype(x.dtype[i], np.number):
KeyError: 'There are no fields in dtype float64.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/danny/Envs/wtest/lib/python3.9/site-packages/weka/core/dataset.py", line 1704, in create_instances_from_matrices
    atts.append(Attribute.create_numeric("x" + str(i+1)))
  File "/home/danny/Envs/wtest/lib/python3.9/site-packages/weka/core/dataset.py", line 1244, in create_numeric
    javabridge.make_instance(
  File "/home/danny/Envs/wtest/lib/python3.9/site-packages/javabridge/jutil.py", line 1717, in make_instance
    klass = get_env().find_class(class_name)
AttributeError: 'NoneType' object has no attribute 'find_class'

**Comment by fracpete** [comment]
Also, you're following the examples for the Python 2.7 version (python-weka-wrapper) rather than the Python 3 version (python-weka-wrapper3):
http://fracpete.github.io/python-weka-wrapper3/examples.html#create-dataset-from-matrices
