### ISSUE TITLE
classify_instance - Null Exception

### ISSUE THREAD

**Issue by nasserbinlaboun** [fracpete/python-weka-wrapper3#36]
When trying to classify an instance
`pred = my_model.classify_instance(inst)`

it shows this error
```
Exception in thread "Thread-0" java.lang.NullPointerException
        weka.core.stemmers.ArabicStemmerKhoja.stem(ArabicStemmerKhoja.java:34)
        weka.classifiers.bayes.NaiveBayesMultinomialText.tokenizeInstance(NaiveBayesMultinomialText.java:413)
        weka.classifiers.bayes.NaiveBayesMultinomialText.distributionForInstance(NaiveBayesMultinomialText.java:303)
        weka.classifiers.AbstractClassifier.classifyInstance(AbstractClassifier.java:173)

        at weka.core.stemmers.ArabicStemmerKhoja.stem(ArabicStemmerKhoja.java:34)
        at weka.classifiers.bayes.NaiveBayesMultinomialText.tokenizeInstance(NaiveBayesMultinomialText.java:413)
        at weka.classifiers.bayes.NaiveBayesMultinomialText.distributionForInstance(NaiveBayesMultinomialText.java:303)
        at weka.classifiers.AbstractClassifier.classifyInstance(AbstractClassifier.java:173)
```

**Comment by fracpete** [comment]
Please supply minimal Python script and dataset to replicate the error with. Also, the `ArabicStemmerKhoja` stemmer does not seem to be one that comes with Weka - is that from an unofficial Weka package or third-party jar? If so, you need to supply links to the source/jar as well.

**Comment by nasserbinlaboun** [comment]
Sorry for being late, and thank you for your fast reply.

another exception related to the previous one
```
Exception in thread "Thread-0" weka.core.UnassignedClassException: Class index is negative (not set)!
        weka.core.Instances.classAttribute(Instances.java:488)
        weka.core.AbstractInstance.classAttribute(AbstractInstance.java:109)

        at weka.core.Instances.classAttribute(Instances.java:488)
        at weka.core.AbstractInstance.classAttribute(AbstractInstance.java:109)
Exception in thread "Thread-0" weka.core.UnassignedClassException: Class index is negative (not set)!
        weka.core.Instances.numClasses(Instances.java:955)
        weka.core.AbstractInstance.numClasses(AbstractInstance.java:370)

        at weka.core.Instances.numClasses(Instances.java:955)
        at weka.core.AbstractInstance.numClasses(AbstractInstance.java:370)
```

`ArabicStemmerKhoja` comes with Weka by default.


### My Code

```
import weka.core.jvm as jvm
from weka.core.converters import Loader
from weka.classifiers import Classifier
import weka.core.serialization as serialization
from weka.core.dataset import Attribute, Instance, Instances

jvm.start(packages=True, max_heap_size="1024m")

model, data = Classifier.deserialize('./classifier.model')

class_att = Attribute.create_nominal("class", ["0", "1"])
text_att = Attribute.create_string("text")

dataset = Instances.create_instances("test", [class_att, text_att], 0)

text2 = "4.وللأسف حتى هذا اليوم لا يتم اتخاذ اى اجرا… "
text3 = "very good"

dataset.add_instance(Instance.create_instance([Instance.missing_value(), text_att.add_string_value(text3)]))
dataset.add_instance(Instance.create_instance([Instance.missing_value(), text_att.add_string_value(text2)]))

for index, inst in enumerate(dataset):
    print(inst.class_index)
    pred = model.classify_instance(inst)
    dist = model.distribution_for_instance(inst)
    print(str(index+1) + ": label index=" + str(pred) + ", class distribution=" + str(dist))

jvm.stop()
```

**Comment by fracpete** [comment]
You are trying to print the `class_index` of your dataset, but you have never set it after you created your dataset. That is why you are getting `UnassignedClassException`.

No, there is no class in Weka that contains `Arabic` in its name (just had a look at the source code of the official packages and the core distribution). The default stemmers are: IteratedLovinsStemmer, LovinsStemmer, NullStemmer, SnowballStemmer

Also, since I don't have access to your model (you are loading a serialized model from disk), I won't be able to execute your code example.

**Comment by nasserbinlaboun** [comment]
My bad, `ArabicStemmerKhoja` comes with this unofficial package:
https://weka.sourceforge.io/packageMetaData/ArabicStemmers_LightStemmers/index.html

Is there any way to use it?

**Comment by fracpete** [comment]
Before trying to script it, can you confirm that you can apply a built model successfully to a test set in the Weka Explorer?
