### ISSUE TITLE
java exception

### ISSUE THREAD

**Issue by alekin2** [fracpete/python-weka-wrapper3#47]
PC configuration :Os windows 10, Python 3.10,Last version of python-weka-wrapper3

After 

jvm.start(packages=True)

I get:

DEBUG:weka.core.jvm:Adding bundled jars
DEBUG:weka.core.jvm:Classpath=['C:\\Users\\utente\\AppData\\Local\\anaconda3\\Lib\\site-packages\\javabridge\\jars\\rhino-1.7R4.jar', 'C:\\Users\\utente\\AppData\\Local\\anaconda3\\Lib\\site-packages\\javabridge\\jars\\runnablequeue.jar', 'C:\\Users\\utente\\AppData\\Local\\anaconda3\\Lib\\site-packages\\javabridge\\jars\\cpython.jar', 'C:\\Users\\utente\\AppData\\Local\\anaconda3\\lib\\site-packages\\weka\\lib\\arpack_combined.jar', 'C:\\Users\\utente\\AppData\\Local\\anaconda3\\lib\\site-packages\\weka\\lib\\core.jar', 'C:\\Users\\utente\\AppData\\Local\\anaconda3\\lib\\site-packages\\weka\\lib\\mtj.jar', 'C:\\Users\\utente\\AppData\\Local\\anaconda3\\lib\\site-packages\\weka\\lib\\python-weka-wrapper.jar', 'C:\\Users\\utente\\AppData\\Local\\anaconda3\\lib\\site-packages\\weka\\lib\\weka.jar']
DEBUG:weka.core.jvm:MaxHeapSize=default
DEBUG:weka.core.jvm:Package support enabled
giu 28, 2023 12:07:11 PM com.github.fommil.netlib.ARPACK <clinit>
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeSystemARPACK
giu 28, 2023 12:07:11 PM com.github.fommil.netlib.ARPACK <clinit>
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeRefARPACK
[WekaPackageManager] Skipping package J48graft because it is not compatible with Weka 3.9.6
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @f98a707
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at weka.core.WekaPackageClassLoaderManager.injectClasses(WekaPackageClassLoaderManager.java:792)
	at weka.core.WekaPackageClassLoaderManager.injectClasses(WekaPackageClassLoaderManager.java:718)
	at weka.core.WekaPackageClassLoaderManager.injectAllClassesInJar(WekaPackageClassLoaderManager.java:667)
	at weka.core.WekaPackageClassLoaderManager.injectAllClassesInJar(WekaPackageClassLoaderManager.java:677)
	at weka.core.WekaPackageLibIsolatingClassLoader.checkForNativeLibs(WekaPackageLibIsolatingClassLoader.java:282)
	at weka.core.WekaPackageLibIsolatingClassLoader.init(WekaPackageLibIsolatingClassLoader.java:145)
	at weka.core.WekaPackageLibIsolatingClassLoader.<init>(WekaPackageLibIsolatingClassLoader.java:126)
	at weka.core.WekaPackageClassLoaderManager.addPackageToClassLoader(WekaPackageClassLoaderManager.java:369)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1373)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1305)
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @f98a707
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at weka.core.WekaPackageClassLoaderManager.injectClasses(WekaPackageClassLoaderManager.java:792)
	at weka.core.WekaPackageClassLoaderManager.injectClasses(WekaPackageClassLoaderManager.java:718)
	at weka.core.WekaPackageClassLoaderManager.injectAllClassesInJar(WekaPackageClassLoaderManager.java:667)
	at weka.core.WekaPackageClassLoaderManager.injectAllClassesInJar(WekaPackageClassLoaderManager.java:677)
	at weka.core.WekaPackageLibIsolatingClassLoader.checkForNativeLibs(WekaPackageLibIsolatingClassLoader.java:282)
	at weka.core.WekaPackageLibIsolatingClassLoader.init(WekaPackageLibIsolatingClassLoader.java:145)
	at weka.core.WekaPackageLibIsolatingClassLoader.<init>(WekaPackageLibIsolatingClassLoader.java:126)
	at weka.core.WekaPackageClassLoaderManager.addPackageToClassLoader(WekaPackageClassLoaderManager.java:369)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1373)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1305)
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @f98a707
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at weka.core.WekaPackageClassLoaderManager.injectClasses(WekaPackageClassLoaderManager.java:792)
	at weka.core.WekaPackageClassLoaderManager.injectClasses(WekaPackageClassLoaderManager.java:718)
	at weka.core.WekaPackageClassLoaderManager.injectAllClassesInJar(WekaPackageClassLoaderManager.java:667)
	at weka.core.WekaPackageClassLoaderManager.injectAllClassesInJar(WekaPackageClassLoaderManager.java:677)
	at weka.core.WekaPackageLibIsolatingClassLoader.checkForNativeLibs(WekaPackageLibIsolatingClassLoader.java:282)
	at weka.core.WekaPackageLibIsolatingClassLoader.init(WekaPackageLibIsolatingClassLoader.java:145)
	at weka.core.WekaPackageLibIsolatingClassLoader.<init>(WekaPackageLibIsolatingClassLoader.java:126)
	at weka.core.WekaPackageClassLoaderManager.addPackageToClassLoader(WekaPackageClassLoaderManager.java:369)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1373)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1305)

**Comment by fracpete** [comment]
What version of Java are you using (`java -version`)?

**Comment by alekin2** [comment]
java -version
java version "16.0.2" 2021-07-20
Java(TM) SE Runtime Environment (build 16.0.2+7-67)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)

**Comment by alekin2** [comment]
JDK_HOME
C:\Program Files\Java\jdk-16.0.2

**Comment by alekin2** [comment]
I changed java to 
openjdk version "17.0.2" 2022-01-18 LTS
OpenJDK Runtime Environment Zulu17.32+13-CA (build 17.0.2+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.32+13-CA (build 17.0.2+8-LTS, mixed mode, sharing)

(weka zulu java distribution)
but it doesn't solve the problem

**Comment by fracpete** [comment]
Please try Java 11 (LTS): https://adoptium.net/

**Comment by alekin2** [comment]
Ok, istalled:
java -version
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

I removed the arpack_combined, core.jar and mtj.jar jars that I had manually added in the anaconda folder to avoid the no/uib/cipr/matrix/Matrix exception

Now I get:
DEBUG:weka.core.jvm:Adding bundled jars
DEBUG:weka.core.jvm:Classpath=['C:\\Users\\myuser\\AppData\\Local\\anaconda3\\Lib\\site-packages\\javabridge\\jars\\rhino-1.7R4.jar', 'C:\\Users\\myuser\\AppData\\Local\\anaconda3\\Lib\\site-packages\\javabridge\\jars\\runnablequeue.jar', 'C:\\Users\\myuser\\AppData\\Local\\anaconda3\\Lib\\site-packages\\javabridge\\jars\\cpython.jar', 'C:\\Users\\myuser\\AppData\\Local\\anaconda3\\lib\\site-packages\\weka\\lib\\python-weka-wrapper.jar', 'C:\\Users\\myuser\\AppData\\Local\\anaconda3\\lib\\site-packages\\weka\\lib\\weka.jar']
DEBUG:weka.core.jvm:MaxHeapSize=default
DEBUG:weka.core.jvm:Package support enabled
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @36f365a0
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at weka.core.WekaPackageClassLoaderManager.injectClasses(WekaPackageClassLoaderManager.java:792)
	at weka.core.WekaPackageClassLoaderManager.injectAllClassesInFromStream(WekaPackageClassLoaderManager.java:690)
	at weka.core.WekaPackageClassLoaderManager.injectMTJCoreClasses(WekaPackageClassLoaderManager.java:118)
	at weka.core.WekaPackageManager.<clinit>(WekaPackageManager.java:255)
java.io.FileNotFoundException: C:\Users\myuser\wekafiles\repCache\simpleEducationalLearningSchemes\1.0.0.props (Impossibile trovare il percorso specificato)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
	at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:189)
	at weka.core.packageManagement.DefaultPackageManager.getRepositoryPackageInfo(DefaultPackageManager.java:332)
	at weka.core.packageManagement.DefaultPackage.getMissingDependencies(DefaultPackage.java:420)
	at weka.core.packageManagement.DefaultPackage.getMissingDependencies(DefaultPackage.java:466)
	at weka.core.WekaPackageManager.loadCheck(WekaPackageManager.java:934)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1365)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1305)
java.io.FileNotFoundException: C:\Users\myuser\wekafiles\repCache\SysFor\1.2.props (Impossibile trovare il percorso specificato)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
	at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:189)
	at weka.core.packageManagement.DefaultPackageManager.getRepositoryPackageInfo(DefaultPackageManager.java:332)
	at weka.core.packageManagement.DefaultPackage.getMissingDependencies(DefaultPackage.java:420)
	at weka.core.packageManagement.DefaultPackage.getMissingDependencies(DefaultPackage.java:466)
	at weka.core.WekaPackageManager.loadCheck(WekaPackageManager.java:934)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1365)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1305)
[WekaPackageManager] Skipping package J48graft because it is not compatible with Weka 3.9.6
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @36f365a0
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at weka.core.WekaPackageClassLoaderManager.injectClasses(WekaPackageClassLoaderManager.java:792)
	at weka.core.WekaPackageClassLoaderManager.injectClasses(WekaPackageClassLoaderManager.java:718)
	at weka.core.WekaPackageClassLoaderManager.injectAllClassesInJar(WekaPackageClassLoaderManager.java:667)
	at weka.core.WekaPackageClassLoaderManager.injectAllClassesInJar(WekaPackageClassLoaderManager.java:677)
	at weka.core.WekaPackageLibIsolatingClassLoader.checkForNativeLibs(WekaPackageLibIsolatingClassLoader.java:282)
	at weka.core.WekaPackageLibIsolatingClassLoader.init(WekaPackageLibIsolatingClassLoader.java:145)
	at weka.core.WekaPackageLibIsolatingClassLoader.<init>(WekaPackageLibIsolatingClassLoader.java:126)
	at weka.core.WekaPackageClassLoaderManager.addPackageToClassLoader(WekaPackageClassLoaderManager.java:369)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1373)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1305)
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @36f365a0
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at weka.core.WekaPackageClassLoaderManager.injectClasses(WekaPackageClassLoaderManager.java:792)
	at weka.core.WekaPackageClassLoaderManager.injectClasses(WekaPackageClassLoaderManager.java:718)
	at weka.core.WekaPackageClassLoaderManager.injectAllClassesInJar(WekaPackageClassLoaderManager.java:667)
	at weka.core.WekaPackageClassLoaderManager.injectAllClassesInJar(WekaPackageClassLoaderManager.java:677)
	at weka.core.WekaPackageLibIsolatingClassLoader.checkForNativeLibs(WekaPackageLibIsolatingClassLoader.java:282)
	at weka.core.WekaPackageLibIsolatingClassLoader.init(WekaPackageLibIsolatingClassLoader.java:145)
	at weka.core.WekaPackageLibIsolatingClassLoader.<init>(WekaPackageLibIsolatingClassLoader.java:126)
	at weka.core.WekaPackageClassLoaderManager.addPackageToClassLoader(WekaPackageClassLoaderManager.java:369)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1373)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1305)
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @36f365a0
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at weka.core.WekaPackageClassLoaderManager.injectClasses(WekaPackageClassLoaderManager.java:792)
	at weka.core.WekaPackageClassLoaderManager.injectClasses(WekaPackageClassLoaderManager.java:718)
	at weka.core.WekaPackageClassLoaderManager.injectAllClassesInJar(WekaPackageClassLoaderManager.java:667)
	at weka.core.WekaPackageClassLoaderManager.injectAllClassesInJar(WekaPackageClassLoaderManager.java:677)
	at weka.core.WekaPackageLibIsolatingClassLoader.checkForNativeLibs(WekaPackageLibIsolatingClassLoader.java:282)
	at weka.core.WekaPackageLibIsolatingClassLoader.init(WekaPackageLibIsolatingClassLoader.java:145)
	at weka.core.WekaPackageLibIsolatingClassLoader.<init>(WekaPackageLibIsolatingClassLoader.java:126)
	at weka.core.WekaPackageClassLoaderManager.addPackageToClassLoader(WekaPackageClassLoaderManager.java:369)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1373)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1305)
java.io.FileNotFoundException: C:\Users\myuser\wekafiles\repCache\SysFor\1.2.props (Impossibile trovare il percorso specificato)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
	at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:189)
	at weka.core.packageManagement.DefaultPackageManager.getRepositoryPackageInfo(DefaultPackageManager.java:332)
	at weka.core.packageManagement.DefaultPackage.getMissingDependencies(DefaultPackage.java:420)
	at weka.core.packageManagement.DefaultPackage.getMissingDependencies(DefaultPackage.java:466)
	at weka.core.WekaPackageManager.loadCheck(WekaPackageManager.java:934)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1365)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1305)
[WekaPackageManager] Skipping package timeseriesForecasting because it is not compatible with Weka 3.9.6
java.io.FileNotFoundException: C:\Users\myuser\wekafiles\repCache\normalize\1.0.1.props (Impossibile trovare il percorso specificato)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
	at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:189)
	at weka.core.packageManagement.DefaultPackageManager.getRepositoryPackageInfo(DefaultPackageManager.java:332)
	at weka.core.packageManagement.DefaultPackage.getMissingDependencies(DefaultPackage.java:420)
	at weka.core.packageManagement.DefaultPackage.getMissingDependencies(DefaultPackage.java:466)
	at weka.core.WekaPackageManager.loadCheck(WekaPackageManager.java:934)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1365)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1305)
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix
	java.base/java.lang.Class.forName0(Native Method)
	java.base/java.lang.Class.forName(Class.java:467)
	weka.core.WekaPackageClassLoaderManager.forName(WekaPackageClassLoaderManager.java:198)
	weka.core.WekaPackageClassLoaderManager.forName(WekaPackageClassLoaderManager.java:178)
	weka.core.ClassDiscovery.find(ClassDiscovery.java:247)
	weka.gui.GenericPropertiesCreator.generateOutputProperties(GenericPropertiesCreator.java:542)
	weka.gui.GenericPropertiesCreator.execute(GenericPropertiesCreator.java:639)
	weka.gui.GenericPropertiesCreator.<clinit>(GenericPropertiesCreator.java:167)
	weka.core.WekaPackageManager.processGenericPropertiesCreatorProps(WekaPackageManager.java:620)
	weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1418)
	weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1305)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at weka.core.WekaPackageClassLoaderManager.forName(WekaPackageClassLoaderManager.java:198)
	at weka.core.WekaPackageClassLoaderManager.forName(WekaPackageClassLoaderManager.java:178)
	at weka.core.ClassDiscovery.find(ClassDiscovery.java:247)
	at weka.gui.GenericPropertiesCreator.generateOutputProperties(GenericPropertiesCreator.java:542)
	at weka.gui.GenericPropertiesCreator.execute(GenericPropertiesCreator.java:639)
	at weka.gui.GenericPropertiesCreator.<clinit>(GenericPropertiesCreator.java:167)
	at weka.core.WekaPackageManager.processGenericPropertiesCreatorProps(WekaPackageManager.java:620)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1418)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1305)
Caused by: java.lang.ClassNotFoundException: no.uib.cipr.matrix.Matrix
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 11 more
Traceback (most recent call last):
  File "C:\Users\myuser\AppData\Local\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-1e9aea12370a>", line 1, in <module>
    jvm.start(packages=True)
  File "C:\Users\myuser\AppData\Local\anaconda3\lib\site-packages\weka\core\jvm.py", line 156, in start
    javabridge.static_call(
  File "C:\Users\myuser\AppData\Local\anaconda3\lib\site-packages\javabridge\jutil.py", line 943, in static_call
    result = fn(*nice_args)
  File "C:\Users\myuser\AppData\Local\anaconda3\lib\site-packages\javabridge\jutil.py", line 923, in fn
    raise JavaException(jexception)
javabridge.jutil.JavaException: no/uib/cipr/matrix/Matrix

**Comment by fracpete** [comment]
You're still using Java 17, not 11. The error that you're encountering is most likely related to [Internal JDK Elements Strongly Encapsulated in JDK 17](https://www.infoq.com/news/2021/06/internals-encapsulated-jdk17/). This is an issue with the python-javabridge library, which pww3 uses under the hood.

**Comment by alekin2** [comment]
you're right, by mistake I downloaded the latest available!
Correct msi is OpenJDK11U-jdk_x64_windows_hotspot_11.0.19_7.msi
and problem is solved!

**Comment by alekin2** [comment]
Thanks so much for your advice
